
emcmake cmake \
  -DCMAKE_SUPPRESS_REGENERATION:BOOL=ON  \
  -DBUILD_USE_PCH:BOOLEAN=OFF \
  -DUSE_TBB:BOOLEAN=OFF \
  -DUSE_TCL:BOOLEAN=OFF \
  -DUSE_FREETYPE:BOOLEAN=OFF \
  -DBUILD_LIBRARY_TYPE=Static \
  -DBUILD_SHARED_LIBS:BOOL=OFF \
  -DBUILD_MODULE_ApplicationFramework:BOOLEAN=OFF \
  -DBUILD_MODULE_DataExchange:BOOLEAN=ON \
  -DBUILD_MODULE_Draw:BOOLEAN=OFF \
  -DBUILD_MODULE_FoundationClasses:BOOLEAN=ON \
  -DBUILD_MODULE_ModelingAlgorithms:BOOLEAN=ON \
  -DBUILD_MODULE_ModelingData:BOOLEAN=ON \
  -DBUILD_MODULE_Visualization:BOOLEAN=OFF \
  -DBUILD_MODULE_CommandInterface:BOOLEAN=ON \
  ../occt